server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fpapi
    username: root
    password: Hermano1738!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
